/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vending_machine;

import java.awt.CardLayout;

/**
 *
 * @author afar0308
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppPanel = new javax.swing.JPanel();
        main_menu = new javax.swing.JPanel();
        lJudul = new javax.swing.JLabel();
        lPilihan = new javax.swing.JLabel();
        daftarMesin = new javax.swing.JComboBox<>();
        bKeluar = new javax.swing.JButton();
        bOk = new javax.swing.JButton();
        snack_icon = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mMenubar = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        mLogin = new javax.swing.JMenuItem();
        mKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AppPanel.setLayout(new java.awt.CardLayout());

        lJudul.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lJudul.setText("SIMULASI VENDING MACHINE");

        lPilihan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lPilihan.setText("Pilihan:");

        daftarMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        snack_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snack_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vending_machine/snack.jpg"))); // NOI18N
        snack_icon.setText("jLabel4");
        snack_icon.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_menuLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addComponent(bKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(snack_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bOk))
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addComponent(lPilihan)
                        .addGap(43, 43, 43)
                        .addComponent(daftarMesin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lJudul))
                .addGap(46, 46, 46))
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lJudul)
                .addGap(38, 38, 38)
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPilihan)
                    .addComponent(daftarMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snack_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bOk)
                            .addComponent(bKeluar))))
                .addGap(56, 56, 56))
        );

        AppPanel.add(main_menu, "card2");

        jLabel2.setText("LOGIN ADMIN");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        AppPanel.add(login, "card3");

        mMenu.setText("Menu");

        mLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mLogin.setText("Login Admin");
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginActionPerformed(evt);
            }
        });
        mMenu.add(mLogin);

        mKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mKeluar.setText("Keluar");
        mKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKeluarActionPerformed(evt);
            }
        });
        mMenu.add(mKeluar);

        mMenubar.add(mMenu);

        setJMenuBar(mMenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ubahJudul(String s) {
        super.setTitle(s);
    }
    
    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void mKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mKeluarActionPerformed

    private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)AppPanel.getLayout();
        cl.show(AppPanel, "card3");
        ubahJudul("Login Admin");
    }//GEN-LAST:event_mLoginActionPerformed

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        // TODO add your handling code here:
        if (daftarMesin.getSelectedIndex() == 0) {
            System.out.println("Anda memilih mesin makanan");
        }
        else if (daftarMesin.getSelectedIndex() == 1) {
            System.out.println("Anda memilih mesin minuman");
        }
    }//GEN-LAST:event_bOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppPanel;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox<String> daftarMesin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lJudul;
    private javax.swing.JLabel lPilihan;
    private javax.swing.JPanel login;
    private javax.swing.JMenuItem mKeluar;
    private javax.swing.JMenuItem mLogin;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuBar mMenubar;
    private javax.swing.JPanel main_menu;
    private javax.swing.JLabel snack_icon;
    // End of variables declaration//GEN-END:variables
}
